"""add models

Revision ID: 32555ae4cbe4
Revises: 
Create Date: 2020-12-06 22:48:10.400403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32555ae4cbe4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
