"""add models

Revision ID: c09cdd845dbc
Revises: 32555ae4cbe4
Create Date: 2020-12-09 00:39:25.223418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09cdd845dbc'
down_revision = '32555ae4cbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
